name: Update docs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  change-favicon:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
  
    - name: Install dependencies
      run: npm install --global jsdoc

    - name: Update docs
      run: jsdoc -d docs main.js modules.js

    - name: Commit & push changes
      run: |
        git add docs
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Copied favicon.ico" && git push || echo "No changes to commit"

