name: Update docs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
  
    - name: Install dependencies
      run: npm install --global jsdoc

    - name: Update docs
      run: jsdoc -d docs main.js modules.js

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Updated JavaScript API documentation
        title: Update docs
        body: Updated JavaScript API documentation
        branch: automated/docs-update
        token: ${{ secrets.PA_TOKEN }}
