name: Sync favicon

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  change-favicon:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: true

    - name: Copy favicon
      run: cp assets/favicons/favicon.ico favicon.ico

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Updated JavaScript API documentation
        title: Update docs
        body: Updated JavaScript API documentation
        branch: automated/docs-update
        token: ${{ secrets.PA_TOKEN }}


